dist: trusty

addons:
  sonarcloud:
    organization: "max-mobility"
    token:
      secure: "JJ2LGK8i3/FShPBaYq+nw+tFmwdOZfWbotBpsNylk/E0CSUp2rgWoCHBNyglHc3Cx+RzCiDjxNrNpN3UVQVYPh5edLIErzMeHKa7sQ7TLZ1dnBwHLTD9FF8CzOA2Dvk16L0xBecIQn4hV/3aPpD8zn1aw+zVRwOjBrAZWuoWjvSG5vjuaVrI1VdyCg5fAMZTQ1iXbEV6H+kvPyVDYe5iF19K+8JMh7/mUBzAPXKlGk+9LFadGorUkNMpX552iDgWWEjFsU31SV90GwJuNXlIUZVG7eKQWOe7tSNoUmfpyZ5mZWtU3cakeHMi1p97jZEPMWpG4EqDi3UnKshTgbClZuyTzCh3nlwZdN2GnfduQKW3UrYkBR9/DcFwUO0XHfJ1x6r5bdmYFAv1QUyaSQwPL3SH183byKQba4NfWaz1w0PjUO12/hvtXCcxk8LQ9wVYyCYyysCGkeDcgGSeSIR/tKyZN4TnQo9axFlTmfudCkBFZlbg+8G7eh3cTkuDL38nsCf1DMZfWhwW5U6Iv3qfMEqpWLuS4AVF9CZQ14a/OGkD8wgtcFjFF2sN8mK9jSMJQthiWMptrb+hXMt0b0I2rPJoDZcpZPff901disFXaTyivkzc3x1D2pe5nBNvoChzLn0HZyzyo+ANcnE7aKfsqt6u4pdWzKfZ8IonlwdGd08="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner