addons:
  sonarcloud:
    organization: "max-mobility"
    token:
      secure: "Ze8iGJhCyX5Uc0IbluQSBnacZCfStXUDuhrYwwbOLXM2ODDMbB9XTwCYa4rfPv2EoaUE87YuygUey4Y53P3pTgSvHQGLmKmgurqpDk+ksrp8HphNoGr3x2ZVMrOsJL/90SAK1W/vweXvWtg5Z0kPtx3jUGpYTsOiIdgYEjqedyWGlqOcjiaPhOcTHpYLdRR3zXZvba/jMnSBB1dEhFRHS+YpznlqALzp8dgIGcSNf4vFhpQRwTWePSkJlfWTbEI1TGpj0LpLYOUE7cLWWdZqAZHb87yi/RqK7k4RPtpe2986g/WxB8CllrKdXPPHZG8kUWQfoFFxl6BIqfKXDFyX9xOKqqVD8kMI41DeWTr9uw0EeJAqaU5AYhwiIMa1zl6hSFL08nEFr2EIEQ0O9BuzibatRLB+TejDVOQ8BCAfZwhD6x+bNXwFnpc+eXcKJTrsYjyd4junqdG0QGyL2iELuAA8so2ys3MXk51wwsnV8D4UwfzYcwzoU2ZM824YuITlwttFb8LiOLXOfGu8bpc04MouZ0NwPQPg57E35IG4aB72vHYW/aMkJmd72tgxbIASnxMdr4K49CqIPc93YBcNQHg0GQZ7jpI5RE6bRIH//8l65gwI2YSYtG9stoygQHW/tAk0tBSdt1Ua9jwphS2cP0n7uhPpjX2iQjEJOC5/uJQ="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner