export enum AppResourceIcons {
  'HOME_ACTIVE' = 'res://home_active',
  'HOME_INACTIVE' = 'res://home_inactive',
  'JOURNEY_ACTIVE' = 'res://journey_active',
  'JOURNEY_INACTIVE' = 'res://journey_inactive',
  'PROFILE_ACTIVE' = 'res://profile_active',
  'PROFILE_INACTIVE' = 'res://profile_inactive',
  'WHEELCHAIR_BLACK' = 'res://accessible_forward_black',
  'BLACK_BACK_NAV' = 'res://round_arrow_back_black_24',
  'WHITE_BACK_NAV' = 'res://round_arrow_back_white_24',
  'WATCH_CHECK_BLACK' = 'res://watch_check_black',
  'WATCH_CHECK_WHITE' = 'res://watch_check_white',
  'WATCH_EMPTY_BLACK' = 'res://watch_empty_black',
  'WATCH_EMPTY_WHITE' = 'res://watch_empty_white',
  'WATCH_QUESTION_BLACK' = 'res://watch_question_black',
  'WATCH_QUESTION_WHITE' = 'res://watch_question_white',
  'WATCH_WAIT_BLACK' = 'res://watch_wait_black',
  'WATCH_WAIT_WHITE' = 'res://watch_wait_white',
  'WATCH_X_BLACK' = 'res://watch_x_black',
  'WATCH_X_WHITE' = 'res://watch_x_white'
}
