export enum STORAGE_KEYS {
  'CURRENT_USER' = 'CURRENT_USER',
  'TOKEN' = 'TOKEN',
  'HAS_PAIRED_TO_PUSHTRACKER' = 'HAS_PAIRED_TO_PUSHTRACKER',
  'APP_THEME' = 'APP_THEME',
  'COAST_TIME_ACTIVITY_GOAL' = 'COAST_TIME_ACTIVITY_GOAL',
  'DISTANCE_ACTIVITY_GOAL' = 'DISTANCE_ACTIVITY_GOAL'
}
