export enum DataKeys {
  'USER_IDENTIFIER' = 'user_identifier',
  'HEART_RATE' = 'heart_rate',
  'WATCH_SERIAL_NUMBER' = 'watch.serial-number',
  'REQUIRE_WATCH_BEING_WORN' = 'watch.require-being-worn',
  'SD_SETTINGS_DIRTY_FLAG' = 'sd.settings.dirty-flag',
  'SD_DISTANCE_CASE' = 'sd.distance.case',
  'SD_DISTANCE_DRIVE' = 'sd.distance.drive',
  'SD_VERSION_MCU' = 'sd.version.mcu',
  'SD_VERSION_BLE' = 'sd.version.ble',
  'SD_BATTERY' = 'sd.battery',
  'SD_SAVED_ADDRESS' = 'sd.saved_address',
  'SD_MAX_SPEED' = 'sd.max_speed',
  'SD_ACCELERATION' = 'sd.acceleration',
  'SD_TAP_SENSITIVITY' = 'sd.tap_sensitivity',
  'SD_CONTROL_MODE' = 'sd.control_mode',
  'SD_UNITS' = 'sd.units',
  'SD_SWITCHCONTROL_MODE' = 'sd.switch_control.mode',
  'SD_SWITCHCONTROL_SPEED' = 'sd.switch_control.speed'
}
