export enum NOTIFICATION_KEYS {
  CHARGING = 'SD_E2_CHARGING_NOTIFICATION',
  SC_LIGHTS = 'SWITCH_CONTROL_LIGHTS_NOTIFICATION',
  ACCELERATE = 'ACCELERATE_WHILE_MOVING_NOTIFICATION',
  SWITCH_CONTROL = 'SWITCH_CONTROL_REMINDER_NOTIFICATION',
  OPEN_PT_WEAR = 'OPEN_PT_WEAR_NOTIFICATION',
  RECURRING = 'RECURRING_NOTIFICATIONS',
  ACCESS_MORE = 'ACCESS_MORE_NOTIFICATION',
  DAILY_DISTANCE = 'DAILY_DISTANCE_NOTIFICATION',
  ODOMETER_RECORDS = 'ODOMETER_RECORDS_NOTIFICATION'
}

/**
 * IDs for SmartDrive Wear Notifications
 */
export enum SmartDriveNotificationIDs {
  TIRE_PRESSURE = 111111,
  SMARTDRIVE_ROLLER_CHECK = 111112,
  SMARTDRIVE_CLAMP_CHECK = 111113,
  OPEN_PT_WEAR = 111114,
  ACCESS_MORE = 111115,
  UNLOCK_MORE = 111116,
  DAILY_DISTANCE = 111117,
  SWITCHCONTROL_REMINDER = 111118,
  ACCELERATE_WHILE_MOVING = 111119,
  SC_LIGHT_INDICATIONS = 111120,
  SD_E2_CHARGING = 111121,
  ODOMETER_RECORDS = 111122,
  ROUTINE_MAINTENANCE = 111123
}
