/**
 * IDs for SmartDrive Wear Notifications
 */
export enum SmartDriveLocalNotifications {
  TIRE_PRESSURE_NOTIFICATION_ID = 111111,
  SMARTDRIVE_MAINTENANCE_NOTIFICATION_ID = 111112
}

/**
 * IDs for PushTracker Wear Notifications
 */
export enum PushTrackerLocalNotifications {
  DAILY_PUSH_WARNING_NOTIFICATION_ID = 111111,
  NEW_COAST_TIME_RECORD_NOTIFICATION_ID = 111112,
  ADD_PT_AS_ELEMENT_NOTIFICATION_ID = 111113,
  GENERAL_WC_MAINTENANCE_REMINDER_NOTIFICATION_ID = 111114
}
