name: App Builds

# Trigger the workflow on push or pull request
on: [push]

jobs:
  lintAndBuild:
    name: Build Apps

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup SSH-Agent
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Setup Permobil-Client
        run: |
          node -v
          npm -v
          npm i && npm i -g rimraf && npm i -g typescript && npm run nuki && npm run setup.all.non-global
          echo no | npm i -g nativescript
          tns usage-reporting disable
          tns error-reporting disable

      - name: Lint
        run: npm run tslint

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install PIP #PIP needed for iOS builds and for TNS CLI to configure correctly on macOS
        run: |
          sudo pip install --upgrade pip
          sudo pip install six

      # - name: Build SD.W
      #   run: |
      #     cd apps/wear/smartdrive
      #     tns build android --env.uglify

      - name: Build PT.M
        run: |
          cd apps/mobile/pushtracker
          tns build android --env.uglify --env.aot
