name: CI

# Trigger the workflow on push or pull request
on: [push]

jobs:
  job1: # App Builds
    name: App Builds
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup SSH-Agent
        uses: webfactory/ssh-agent@support-multiple-keys
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
            ${{ secrets.SQLITE_ENCRYPTED_SSH_TOKEN }}
            ${{ secrets.SQLITE_COMMERCIAL_SSH_TOKEN }}

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install PIP #PIP needed for iOS builds and for TNS CLI to configure correctly on macOS
        run: |
          sudo pip install --upgrade pip
          sudo pip install six

      - name: Setup Permobil-Client
        run: |
          echo no | npm i -g nativescript
          tns usage-reporting disable
          tns error-reporting disable
          npm run global.installs
          npm i && npm run clean.all
          npm run setup.@permobil
          npm run setup.forked.plugins
          npm run setup.mobile

      - name: Lint
        run: npm run tslint

      - name: Build PT.M Android
        run: |
          cd apps/mobile/pushtracker
          tns build android --env.aot --env.uglify

      # - name: Build PT.W Android
      #   run: |
      #     cd apps/wear/pushtracker
      #     tns build android --env.uglify

      # - name: Build SD.W Android
      #   run: |
      #     cd apps/wear/smartdrive
      #     tns build android --env.uglify

      - name: Build PT.M iOS
        run: |
          cd apps/mobile/pushtracker
          tns build ios --env.aot --env.uglify
