name: App Builds

# Trigger the workflow on push or pull request
on: [push]

jobs:
  lintAndBuild:
    name: Build Apps

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup SSH-Agent
        uses: webfactory/ssh-agent@support-multiple-keys
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}, |
            ${{ secrets.SQLITE_ENCRYPTED_SSH_TOKEN }} |
            ${{ secrets.SQLITE_COMMERCIAL_SSH_TOKEN }}

      # - name: Add Keys for Private Deps
      #   with: # Set the secret as an input
      #     SQLITE_COMMERCIAL_SSH_TOKEN: ${{ secrets.SQLITE_COMMERCIAL_SSH_TOKEN }}
      #     SQLITE_ENCRYPTED_SSH_TOKEN: ${{ secrets.SQLITE_ENCRYPTED_SSH_TOKEN }}
      #   run: |
      #     ssh-add - <<< ${{ SQLITE_COMMERCIAL_SSH_TOKEN }}
      #     ssh-add - <<< ${{ SQLITE_ENCRYPTED_SSH_TOKEN }}

      - name: Setup Permobil-Client
        run: |
          echo no | npm i -g nativescript
          tns usage-reporting disable
          tns error-reporting disable
          npm i && npm i -g rimraf && npm i -g typescript && npm run nuki && npm run setup.all.non-global

      - name: Lint
        run: npm run tslint

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install PIP #PIP needed for iOS builds and for TNS CLI to configure correctly on macOS
        run: |
          sudo pip install --upgrade pip
          sudo pip install six

      - name: Build PT.M
        run: |
          cd apps/mobile/pushtracker
          tns build android --env.aot

      - name: Build SD.W
        run: |
          cd apps/wear/smartdrive
          tns build android

      - name: Build PT.W
        run: |
          cd apps/wear/pushtracker
          tns build android
