name: CI

# Trigger the workflow on push or pull request
on: [push]

jobs:
  analysisAndBuild:
    name: Analysis

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup SSH-Agent
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Setup Permobil-Client
        run: |
          npm i && npm run setup.all.non-global
          echo no | npm i -g nativescript
          tns usage-reporting disable
          tns error-reporting disable

      - name: Lint
        run: npm run tslint

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build SD.W
        run: |
          cd apps/wear/smartdrive
          tns build android --env.uglify
