name: CI

# Trigger the workflow on push or pull request
# on: [push]

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  # setupProject:
  #   name: Project Setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Lint
  #       run: npm i && npm run setup.all.non-global

  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
      - uses: actions/checkout@v1
      - uses: sonarsource/sonarcloud-github-action@master
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: npm i
  tsLint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Lint
      - uses: actions/checkout@v1
      - run: npm i && npm run tslint
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: SonarCloud Analysis
  #       run: sonar-scanner
  #     - name: Run a multi-line script
  #       run: |
  #         sonar-scanner
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@v1.1
  #       run: sonar-scanner
