name: CI

# Trigger the workflow on push or pull request
on: [push]

jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  tsLint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint
        run: npm i && npm run tslint


  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: SonarCloud Analysis
  #       run: sonar-scanner
  #     - name: Run a multi-line script
  #       run: |
  #         sonar-scanner
  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@v1.1
  #       run: sonar-scanner
