name: CI

# Trigger the workflow on push or pull request
on: [push]

jobs:
  job1:
    name: PT.M Android Build
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup SSH-Agent
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Permobil-Client
        run: |
          echo no | npm i -g nativescript
          tns usage-reporting disable
          tns error-reporting disable
          npm run setup.all

      - name: Lint
        run: npm run tslint

      - name: Build PT.M Android
        run: |
          cd apps/mobile/pushtracker
          tns build android --env.aot --env.uglify

  job2:
    name: PT.M iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup SSH-Agent
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install PIP #PIP needed for iOS builds and for TNS CLI to configure correctly on macOS
        run: |
          sudo pip install --upgrade pip
          sudo pip install six

      - name: Setup Permobil-Client
        run: |
          echo no | npm i -g nativescript
          tns usage-reporting disable
          tns error-reporting disable
          npm run setup.all

      - name: Build PT.M iOS
        run: |
          cd apps/mobile/pushtracker
          tns build ios --env.aot --env.uglify
